import { Injectable, NotFoundException } from '@nestjs/common';
import { GraphService } from '../graph/graph.service';
import { TerraformGeneratorService } from './generators/terraform.generator';
import type { GeneratedFile, IaCFormat } from '../common/types/infra-ir.types';

@Injectable()
export class ExportService {
  constructor(
    private readonly graphService: GraphService,
    private readonly terraformGenerator: TerraformGeneratorService,
  ) {}

  /**
   * Generate IaC files from a project's architecture graph.
   */
  async generateIaC(
    projectId: string,
    versionNum: number,
    format: IaCFormat,
  ): Promise<GeneratedFile[]> {
    const graph = await this.graphService.getFullGraph(projectId, versionNum);

    switch (format) {
      case 'terraform':
        return this.terraformGenerator.generate(graph);

      case 'ansible':
        // Ansible generator placeholder — Phase 2 extension
        return [
          {
            filename: 'playbook.yml',
            content: this.generateAnsibleStub(graph),
            language: 'yaml',
          },
        ];

      default:
        throw new NotFoundException(`Format IaC "${format}" non supporté`);
    }
  }

  /**
   * Export the graph as structured JSON (platform interchange format).
   */
  async exportJSON(
    projectId: string,
    versionNum: number,
  ): Promise<GeneratedFile[]> {
    const graph = await this.graphService.getFullGraph(projectId, versionNum);

    return [
      {
        filename: `architecture_${projectId}_v${versionNum}.json`,
        content: JSON.stringify(graph, null, 2),
        language: 'json',
      },
    ];
  }

  private generateAnsibleStub(graph: any): string {
    const hosts = graph.nodes
      .filter(
        (n: any) =>
          n.resourceType === 'virtual-machine' ||
          n.resourceType === 'physical-server',
      )
      .map((n: any) => `    ${n.logicalName}:
      ansible_host: ${n.properties.ip || '{{ lookup("env", "HOST_IP") }}'}`)
      .join('\n');

    return `---
# Ansible inventory generated by ArchPlatform
# Project: ${graph.projectId}

all:
  hosts:
${hosts || '    # No compute instances found'}

  vars:
    ansible_user: deploy
    ansible_become: true
`;
  }
}
