import { Injectable } from '@nestjs/common';
import type {
  InfraNode,
  InfraEdge,
  InfraGraphDTO,
  GeneratedFile,
  ProviderMapping,
} from '../../common/types/infra-ir.types';

interface SemanticResource {
  node: InfraNode;
  terraformType: string;
  resolvedProperties: Record<string, unknown>;
  dependsOn: string[]; // IDs of resources this depends on
  outputs: { name: string; expression: string }[];
}

@Injectable()
export class TerraformGeneratorService {
  /**
   * Provider mapping table: canonical type → Terraform resource type.
   */
  private static readonly PROVIDER_MAP: Record<
    string,
    Record<string, ProviderMapping>
  > = {
    aws: {
      vpc: { terraform: 'aws_vpc', pulumi: 'aws.ec2.Vpc' },
      subnet: { terraform: 'aws_subnet', pulumi: 'aws.ec2.Subnet' },
      'internet-gateway': {
        terraform: 'aws_internet_gateway',
        pulumi: 'aws.ec2.InternetGateway',
      },
      'nat-gateway': {
        terraform: 'aws_nat_gateway',
        pulumi: 'aws.ec2.NatGateway',
      },
      'route-table': {
        terraform: 'aws_route_table',
        pulumi: 'aws.ec2.RouteTable',
      },
      'virtual-machine': {
        terraform: 'aws_instance',
        pulumi: 'aws.ec2.Instance',
      },
      'container-cluster': {
        terraform: 'aws_ecs_cluster',
        pulumi: 'aws.ecs.Cluster',
      },
      'serverless-function': {
        terraform: 'aws_lambda_function',
        pulumi: 'aws.lambda.Function',
      },
      'security-group': {
        terraform: 'aws_security_group',
        pulumi: 'aws.ec2.SecurityGroup',
      },
      waf: { terraform: 'aws_wafv2_web_acl', pulumi: 'aws.wafv2.WebAcl' },
      'relational-database': {
        terraform: 'aws_db_instance',
        pulumi: 'aws.rds.Instance',
      },
      'object-storage': {
        terraform: 'aws_s3_bucket',
        pulumi: 'aws.s3.Bucket',
      },
      'load-balancer': { terraform: 'aws_lb', pulumi: 'aws.lb.LoadBalancer' },
      cdn: {
        terraform: 'aws_cloudfront_distribution',
        pulumi: 'aws.cloudfront.Distribution',
      },
      'dns-zone': { terraform: 'aws_route53_zone', pulumi: 'aws.route53.Zone' },
    },
    gcp: {
      vpc: {
        terraform: 'google_compute_network',
        pulumi: 'gcp.compute.Network',
      },
      subnet: {
        terraform: 'google_compute_subnetwork',
        pulumi: 'gcp.compute.Subnetwork',
      },
      'virtual-machine': {
        terraform: 'google_compute_instance',
        pulumi: 'gcp.compute.Instance',
      },
      'relational-database': {
        terraform: 'google_sql_database_instance',
        pulumi: 'gcp.sql.DatabaseInstance',
      },
      firewall: {
        terraform: 'google_compute_firewall',
        pulumi: 'gcp.compute.Firewall',
      },
      'load-balancer': {
        terraform: 'google_compute_forwarding_rule',
        pulumi: 'gcp.compute.ForwardingRule',
      },
      'object-storage': {
        terraform: 'google_storage_bucket',
        pulumi: 'gcp.storage.Bucket',
      },
    },
    azure: {
      vpc: {
        terraform: 'azurerm_virtual_network',
        pulumi: 'azure.network.VirtualNetwork',
      },
      subnet: { terraform: 'azurerm_subnet', pulumi: 'azure.network.Subnet' },
      'virtual-machine': {
        terraform: 'azurerm_linux_virtual_machine',
        pulumi: 'azure.compute.LinuxVirtualMachine',
      },
      'relational-database': {
        terraform: 'azurerm_postgresql_flexible_server',
        pulumi: 'azure.postgresql.FlexibleServer',
      },
      'security-group': {
        terraform: 'azurerm_network_security_group',
        pulumi: 'azure.network.NetworkSecurityGroup',
      },
    },
  };

  /**
   * Generate a complete Terraform project from an InfraGraph.
   */
  generate(graph: InfraGraphDTO): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. Resolve all nodes into semantic resources
    const resources = this.resolveAll(graph);

    // 2. Topological sort (dependency order)
    const sorted = this.topologicalSort(resources);

    // 3. Generate provider.tf
    files.push({
      filename: 'provider.tf',
      content: this.generateProvider(graph.provider),
      language: 'hcl',
    });

    // 4. Generate variables.tf
    files.push({
      filename: 'variables.tf',
      content: this.generateVariables(graph.provider),
      language: 'hcl',
    });

    // 5. Generate main.tf
    const mainBlocks: string[] = [
      `# ════════════════════════════════════════════════════`,
      `# main.tf — Generated by ArchPlatform IaC Compiler`,
      `# Project: ${graph.projectId}`,
      `# Date:    ${new Date().toISOString()}`,
      `# ════════════════════════════════════════════════════`,
      '',
    ];
    for (const resource of sorted) {
      mainBlocks.push(this.generateResourceBlock(resource, sorted));
    }
    files.push({
      filename: 'main.tf',
      content: mainBlocks.join('\n'),
      language: 'hcl',
    });

    // 6. Generate outputs.tf
    files.push({
      filename: 'outputs.tf',
      content: this.generateOutputs(sorted),
      language: 'hcl',
    });

    return files;
  }

  // ══════════════════════════════════════
  // Semantic Resolution
  // ══════════════════════════════════════

  private resolveAll(graph: InfraGraphDTO): SemanticResource[] {
    const resources: SemanticResource[] = [];

    for (const node of graph.nodes) {
      const mapping =
        TerraformGeneratorService.PROVIDER_MAP[node.provider]?.[
          node.resourceType
        ];
      if (!mapping) {
        // Skip unknown resource types (on-premise physical devices)
        continue;
      }

      resources.push({
        node,
        terraformType: mapping.terraform,
        resolvedProperties: this.resolveProperties(node),
        dependsOn: this.inferDependencies(node, graph),
        outputs: this.inferOutputs(node, mapping.terraform),
      });
    }

    return resources;
  }

  private resolveProperties(
    node: InfraNode,
  ): Record<string, unknown> {
    const p = node.properties;
    const resolvers: Record<
      string,
      (props: Record<string, unknown>) => Record<string, unknown>
    > = {
      'aws/vpc': (props) => ({
        cidr_block: props.cidr,
        enable_dns_hostnames: props.dnsHostnames ?? true,
        enable_dns_support: props.dnsSupport ?? true,
      }),
      'aws/subnet': (props) => ({
        cidr_block: props.cidr,
        availability_zone: props.az,
        map_public_ip_on_launch: props.isPublic ?? false,
      }),
      'aws/virtual-machine': (props) => ({
        ami: props.ami ?? 'ami-0c55b159cbfafe1f0',
        instance_type: props.instanceType ?? 't3.micro',
        key_name: props.keyPair,
      }),
      'aws/relational-database': (props) => ({
        engine: props.engine ?? 'postgres',
        engine_version: props.engineVersion ?? '15.4',
        instance_class: props.instanceClass ?? 'db.t3.micro',
        allocated_storage: props.storage ?? 20,
        db_name: props.dbName,
        username: props.masterUsername ?? 'admin',
        skip_final_snapshot: true,
      }),
      'aws/security-group': (props) => ({
        name: props.name,
        description: props.description,
      }),
      'aws/object-storage': (props) => ({
        bucket: props.bucketName,
      }),
      'aws/load-balancer': (props) => ({
        internal: props.scheme === 'internal',
        load_balancer_type: props.lbType ?? 'application',
      }),
      'gcp/vpc': (props) => ({
        name: props.name,
        auto_create_subnetworks: props.autoCreateSubnetworks ?? false,
        routing_mode: props.routingMode ?? 'REGIONAL',
      }),
      'gcp/virtual-machine': (props) => ({
        machine_type: props.machineType ?? 'e2-micro',
        zone: props.zone ?? 'europe-west1-b',
      }),
    };

    const key = `${node.provider}/${node.resourceType}`;
    const resolver = resolvers[key];
    return resolver ? resolver(p) : p;
  }

  private inferDependencies(
    node: InfraNode,
    graph: InfraGraphDTO,
  ): string[] {
    const deps: string[] = [];

    // Parent hierarchy = dependency (subnet depends on VPC)
    if (node.parentId) {
      deps.push(node.parentId);
    }

    // Edges where this node is the target of 'secures' or 'contains'
    for (const edge of graph.edges) {
      if (edge.targetId === node.id && edge.edgeType === 'secures') {
        deps.push(edge.sourceId);
      }
    }

    return deps;
  }

  private inferOutputs(
    node: InfraNode,
    tfType: string,
  ): { name: string; expression: string }[] {
    const name = this.sanitizeName(node.logicalName);
    const outputs: { name: string; expression: string }[] = [];

    if (tfType === 'aws_instance') {
      outputs.push({
        name: `${name}_public_ip`,
        expression: `${tfType}.${name}.public_ip`,
      });
    }
    if (tfType === 'aws_vpc') {
      outputs.push({
        name: `${name}_id`,
        expression: `${tfType}.${name}.id`,
      });
    }
    if (tfType === 'aws_db_instance') {
      outputs.push({
        name: `${name}_endpoint`,
        expression: `${tfType}.${name}.endpoint`,
      });
    }

    return outputs;
  }

  // ══════════════════════════════════════
  // Topological Sort (Kahn's Algorithm)
  // ══════════════════════════════════════

  private topologicalSort(resources: SemanticResource[]): SemanticResource[] {
    const inDegree = new Map<string, number>();
    const adjacency = new Map<string, string[]>();
    const resourceMap = new Map<string, SemanticResource>();

    for (const res of resources) {
      resourceMap.set(res.node.id, res);
      inDegree.set(res.node.id, 0);
      adjacency.set(res.node.id, []);
    }

    for (const res of resources) {
      for (const depId of res.dependsOn) {
        if (resourceMap.has(depId)) {
          adjacency.get(depId)!.push(res.node.id);
          inDegree.set(
            res.node.id,
            (inDegree.get(res.node.id) || 0) + 1,
          );
        }
      }
    }

    const queue: string[] = [];
    for (const [id, degree] of inDegree) {
      if (degree === 0) queue.push(id);
    }

    const sorted: SemanticResource[] = [];
    while (queue.length > 0) {
      const current = queue.shift()!;
      sorted.push(resourceMap.get(current)!);

      for (const neighbor of adjacency.get(current) || []) {
        const newDegree = (inDegree.get(neighbor) || 0) - 1;
        inDegree.set(neighbor, newDegree);
        if (newDegree === 0) queue.push(neighbor);
      }
    }

    // If cycle detected, append remaining in original order
    if (sorted.length !== resources.length) {
      const sortedIds = new Set(sorted.map((r) => r.node.id));
      for (const res of resources) {
        if (!sortedIds.has(res.node.id)) sorted.push(res);
      }
    }

    return sorted;
  }

  // ══════════════════════════════════════
  // HCL Code Generation
  // ══════════════════════════════════════

  private generateResourceBlock(
    resource: SemanticResource,
    allResources: SemanticResource[],
  ): string {
    const { terraformType, node, resolvedProperties, dependsOn } = resource;
    const name = this.sanitizeName(node.logicalName);

    const lines: string[] = [];
    lines.push(`resource "${terraformType}" "${name}" {`);

    // Scalar properties
    for (const [key, value] of Object.entries(resolvedProperties)) {
      if (value === undefined || value === null) continue;
      lines.push(`  ${key} = ${this.hclValue(value)}`);
    }

    // Dependency references (e.g., vpc_id = aws_vpc.main.id)
    for (const depId of dependsOn) {
      const depResource = allResources.find((r) => r.node.id === depId);
      if (depResource) {
        const refAttr = this.inferReferenceAttribute(resource, depResource);
        if (refAttr) {
          const depName = this.sanitizeName(depResource.node.logicalName);
          lines.push(
            `  ${refAttr.property} = ${depResource.terraformType}.${depName}.${refAttr.attribute}`,
          );
        }
      }
    }

    // Security group ingress/egress blocks (inline)
    if (terraformType === 'aws_security_group') {
      const ingress = (node.properties.ingressRules as any[]) || [];
      const egress = (node.properties.egressRules as any[]) || [];

      for (const rule of ingress) {
        lines.push('');
        lines.push('  ingress {');
        lines.push(`    from_port   = ${rule.port ?? 0}`);
        lines.push(`    to_port     = ${rule.port ?? 0}`);
        lines.push(`    protocol    = "${rule.protocol ?? 'tcp'}"`);
        lines.push(
          `    cidr_blocks = [${this.hclValue(rule.source ?? '0.0.0.0/0')}]`,
        );
        lines.push('  }');
      }

      for (const rule of egress) {
        lines.push('');
        lines.push('  egress {');
        lines.push(`    from_port   = ${rule.port ?? 0}`);
        lines.push(`    to_port     = ${rule.port ?? 0}`);
        lines.push(
          `    protocol    = "${rule.protocol ?? '-1'}"`,
        );
        lines.push(
          `    cidr_blocks = [${this.hclValue(rule.source ?? '0.0.0.0/0')}]`,
        );
        lines.push('  }');
      }
    }

    // Tags
    if (node.tags && Object.keys(node.tags).length > 0) {
      lines.push('');
      lines.push('  tags = {');
      for (const [k, v] of Object.entries(node.tags)) {
        lines.push(`    ${k} = "${v}"`);
      }
      lines.push('    ManagedBy = "archplatform"');
      lines.push('  }');
    } else {
      lines.push('');
      lines.push('  tags = {');
      lines.push(`    Name      = "${node.logicalName}"`);
      lines.push('    ManagedBy = "archplatform"');
      lines.push('  }');
    }

    lines.push('}');
    lines.push('');
    return lines.join('\n');
  }

  /**
   * Infer the reference attribute between child and parent resources.
   */
  private inferReferenceAttribute(
    child: SemanticResource,
    parent: SemanticResource,
  ): { property: string; attribute: string } | null {
    const refMap: Record<
      string,
      Record<string, { property: string; attribute: string }>
    > = {
      aws_subnet: {
        aws_vpc: { property: 'vpc_id', attribute: 'id' },
      },
      aws_instance: {
        aws_subnet: { property: 'subnet_id', attribute: 'id' },
        aws_security_group: {
          property: 'vpc_security_group_ids',
          attribute: 'id',
        },
      },
      aws_security_group: {
        aws_vpc: { property: 'vpc_id', attribute: 'id' },
      },
      aws_internet_gateway: {
        aws_vpc: { property: 'vpc_id', attribute: 'id' },
      },
      aws_nat_gateway: {
        aws_subnet: { property: 'subnet_id', attribute: 'id' },
      },
      aws_route_table: {
        aws_vpc: { property: 'vpc_id', attribute: 'id' },
      },
      aws_db_instance: {
        aws_security_group: {
          property: 'vpc_security_group_ids',
          attribute: 'id',
        },
      },
      aws_lb: {
        aws_subnet: { property: 'subnets', attribute: 'id' },
        aws_security_group: {
          property: 'security_groups',
          attribute: 'id',
        },
      },
      google_compute_subnetwork: {
        google_compute_network: { property: 'network', attribute: 'id' },
      },
      google_compute_instance: {
        google_compute_subnetwork: {
          property: 'subnetwork',
          attribute: 'id',
        },
      },
    };

    return (
      refMap[child.terraformType]?.[parent.terraformType] ?? null
    );
  }

  // ══════════════════════════════════════
  // File generators
  // ══════════════════════════════════════

  private generateProvider(provider: string): string {
    const providers: Record<string, string> = {
      aws: `terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}`,
      gcp: `terraform {
  required_version = ">= 1.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
}`,
      azure: `terraform {
  required_version = ">= 1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}`,
    };
    return providers[provider] ?? providers['aws'];
  }

  private generateVariables(provider: string): string {
    const vars: Record<string, string> = {
      aws: `variable "aws_region" {
  description = "Région AWS pour le déploiement"
  type        = string
  default     = "eu-west-3"
}

variable "environment" {
  description = "Environnement de déploiement"
  type        = string
  default     = "production"
}`,
      gcp: `variable "gcp_project_id" {
  description = "ID du projet GCP"
  type        = string
}

variable "gcp_region" {
  description = "Région GCP"
  type        = string
  default     = "europe-west1"
}

variable "environment" {
  description = "Environnement de déploiement"
  type        = string
  default     = "production"
}`,
    };
    return vars[provider] ?? vars['aws'];
  }

  private generateOutputs(resources: SemanticResource[]): string {
    const lines: string[] = [];
    for (const res of resources) {
      for (const output of res.outputs) {
        lines.push(`output "${output.name}" {`);
        lines.push(`  value = ${output.expression}`);
        lines.push('}');
        lines.push('');
      }
    }
    return lines.length > 0
      ? lines.join('\n')
      : '# No outputs generated';
  }

  // ══════════════════════════════════════
  // Utilities
  // ══════════════════════════════════════

  private hclValue(value: unknown): string {
    if (typeof value === 'string') return `"${value}"`;
    if (typeof value === 'boolean') return value.toString();
    if (typeof value === 'number') return value.toString();
    if (Array.isArray(value))
      return `[${value.map((v) => this.hclValue(v)).join(', ')}]`;
    return JSON.stringify(value);
  }

  private sanitizeName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9_]/g, '_')
      .replace(/^_+|_+$/g, '')
      .replace(/_+/g, '_');
  }
}
